apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: book4u-tls
spec:
  secretName: book4u-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: book4u.club
  dnsNames:
    - book4u.club
    - www.book4u.club
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - book4u.club
          - www.book4u.club